[Personal (Gmail)]
source        = imaps://masaru.nakabayashi%40gmail.com:kjfgkjstwjavrrcf@imap.gmail.com:993
outgoing      = smtps://masaru.nakabayashi%40gmail.com:kjfgkjstwjavrrcf@smtp.gmail.com:587
default       = INBOX
from          = Masaru Nakabayashi <masaru.nakabayashi@gmail.com>
cache-headers = true
